### DISCUSSION TITLE
How to setup cluster

### DISCUSSION THREAD

**Discussion by NirnayK** [infiniflow/infinity#2545] [Q&A]
I am setting infinity by setting following yaml using the yaml give below 
and then running the api role apis but it is giving me error saying that it is setup in standalone mode

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ragflow-infinity
  namespace: ragflow
  labels:
    app: ragflow-infinity
spec:
  serviceName: "ragflow-infinity-service"
  replicas: 3
  selector:
    matchLabels:
      app: ragflow-infinity
  template:
    metadata:
      labels:
        app: ragflow-infinity
    spec:
      # affinity:
      #   podAntiAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #     - labelSelector:
      #         matchLabels:
      #           app: ragflow-infinity
      #       topologyKey: "kubernetes.io/hostname"
      nodeSelector:
        node.tir.e2enetworks.net/label: ragflow-services
      containers:
      - name: infinity
        image: infiniflow/infinity:v0.6.0-dev3
        resources:
{{ toYaml .Values.infinity.resources | indent 10 }}
        env:
        - name: server_mode
          value: "admin"
        - name: storage_type
          value: "minio"
        - name: peer_ip
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: peer_port
          value: "23851"
        - name: network.host
          value: "0.0.0.0"
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MINIO_ENDPOINT
          value: "http://ragflow-minio-service.ragflow.svc.cluster.local:9000"
        envFrom:
        - secretRef:
            name: ragflow-secrets
        ports:
        - containerPort: 23817
          name: thrift
        - containerPort: 23820
          name: http
        - containerPort: 5432
          name: psql
        readinessProbe:
          httpGet:
            path: /admin/node/current
            port: 23820
          initialDelaySeconds: 60
          periodSeconds: 30
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /admin/node/current
            port: 23820
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 120
        securityContext:
          capabilities:
            add:
              - "NET_BIND_SERVICE"
          seccompProfile:
            type: RuntimeDefault
---
apiVersion: v1
kind: Service
metadata:
  name: ragflow-infinity-service
  namespace: ragflow
  labels:
    app: ragflow-infinity
spec:
  ports:
    - name: thrift
      port: 23817
      targetPort: 23817
      protocol: TCP
    - name: http
      port: 23820
      targetPort: 23820
      protocol: TCP
    - name: mysql
      port: 5432
      targetPort: 5432
      protocol: TCP
  type: ClusterIP
  selector:
    app: ragflow-infinity

```
